package Karyawan.View;

import Karyawan.Kontrol.GajiKontroller;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author pitokdf
 */
public class formGaji extends javax.swing.JFrame {

    GajiKontroller kontrol;

    /**
     * Creates new form formGaji
     */
    public formGaji() {
        initComponents();
        kontrol = new GajiKontroller(this);
        kontrol.cls();
        kontrol.isiCombo();
        kontrol.tampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public javax.swing.JTextField getTxtBulan() {
        return txtBulan;
    }

    public javax.swing.JTextField getTxtTahun() {
        return txtTahun;
    }

    public javax.swing.JComboBox<String> getCboKaryawan() {
        return cboNIP;
    }

    public javax.swing.JTable getTblGaji() {
        return tblGaji;
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboNIP = new javax.swing.JComboBox<>();
        txtBulan = new javax.swing.JTextField();
        txtTahun = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGaji = new javax.swing.JTable();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("NIP");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(59, 34, 67, 41);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Bulan");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(385, 34, 67, 41);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Tahun");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(777, 34, 67, 41);

        cboNIP.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        cboNIP.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cboNIP);
        cboNIP.setBounds(138, 35, 188, 41);

        txtBulan.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        txtBulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBulanActionPerformed(evt);
            }
        });
        getContentPane().add(txtBulan);
        txtBulan.setBounds(470, 34, 268, 42);

        txtTahun.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        getContentPane().add(txtTahun);
        txtTahun.setBounds(862, 34, 264, 42);

        tblGaji.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tblGaji.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null }
                },
                new String[] {
                        "NIP", "Bulan", "Tahun", "Gaji Pokok", "Tunjangan Anak", "Tunjangan Istri", "Total"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        tblGaji.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGajiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblGaji);
        if (tblGaji.getColumnModel().getColumnCount() > 0) {
            tblGaji.getColumnModel().getColumn(0).setResizable(false);
            tblGaji.getColumnModel().getColumn(1).setResizable(false);
            tblGaji.getColumnModel().getColumn(2).setResizable(false);
            tblGaji.getColumnModel().getColumn(3).setResizable(false);
            tblGaji.getColumnModel().getColumn(4).setResizable(false);
            tblGaji.getColumnModel().getColumn(5).setResizable(false);
            tblGaji.getColumnModel().getColumn(6).setResizable(false);
        }

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(70, 188, 1067, 480);

        btnInsert.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert);
        btnInsert.setBounds(70, 109, 104, 42);

        btnUpdate.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(220, 110, 104, 42);

        btnDelete.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(370, 110, 104, 42);

        btnBatal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        getContentPane().add(btnBatal);
        btnBatal.setBounds(520, 110, 104, 42);

        setSize(new java.awt.Dimension(1183, 741));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBulanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtBulanActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtBulanActionPerformed

    private void tblGajiMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tblGajiMouseClicked
        // TODO add your handling code here:
        kontrol.getGaji();
    }// GEN-LAST:event_tblGajiMouseClicked

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        kontrol.saveGaji();
        kontrol.tampilData();
        kontrol.cls();
    }// GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        kontrol.updateGaji();
        kontrol.tampilData();
        kontrol.cls();
    }// GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        kontrol.deleteGaji();
        kontrol.tampilData();
        kontrol.cls();
    }// GEN-LAST:event_btnDeleteActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        kontrol.cls();
    }// GEN-LAST:event_btnBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(formGaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } //catch (InstantiationException ex) {
        //     java.util.logging.Logger.getLogger(formGaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        // } catch (IllegalAccessException ex) {
        //     java.util.logging.Logger.getLogger(formGaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        // } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        //     java.util.logging.Logger.getLogger(formGaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        // }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formGaji().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboNIP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable tblGaji;
    private javax.swing.JTextField txtBulan;
    private javax.swing.JTextField txtTahun;
    // End of variables declaration//GEN-END:variables
}
